### ISSUE TITLE
✨ 新規登録画面の作り直し

### ISSUE THREAD

**Issue by shion1305** [shion1305/ynufes-mypage-frontend#27]
### TODO (実装する内容)

新規登録画面は現状完全にVuetifyに依存している。
方針について検討したうえで改善することが必要

### Impact (実装による変更の影響範囲)

(方針の検討段階)
- pages/welcome.vue

**Comment by tomoyahiroe** [comment]
- removed vuetify(#28)
- create welcome page (#47)
