### ISSUE TITLE
🐛 WelcomeページでのType Checkエラー

### ISSUE THREAD

**Issue by Shion1305** [shion1305/ynufes-mypage-frontend#49]
### Summary (バグの概要)

![image](https://github.com/shion1305/ynufes-mypage-frontend/assets/20254962/d7912d86-3e94-4060-a5cd-944bec6b2393)

### Reproduction Steps (バグ発生条件)

Welcomeページを開いた時

### Probable Cause (修正が必要と思われる箇所)

https://github.com/shion1305/ynufes-mypage-frontend/blob/d100b54252cb85f58146d0e10e84fd854e634d63/pages/welcome.vue#L138

**Comment by tomoyahiroe** [comment]
I fixed this bug by #54.
