### ISSUE TITLE
🐛 Sidebar, loginページのレスポンシブ対応

### ISSUE THREAD

**Issue by shion1305** [shion1305/ynufes-mypage-frontend#6]
# 提案の概要
- 実装済みのSidebarのレスポンシブ対応(モバイル時のメニューの実装)
- loginページのレスポンシブ対応
- 画面サイズの100vhの解消

# 提案による変更の影響範囲
- 現在実装済みのすべての範囲

# 補足・考慮すべきこと
- あらゆるスクリーンサイズでしっかり表示が崩れないか
- breakpointが守られているか

**Comment by tomoyahiroe** [comment]
ページのメインエリアの要素に対してmax-widthとmx-auto(vuetifyの中央揃え)指定した方が良いよなー
