### ISSUE TITLE
:sparkles: [Figma]Homeページの Form コンテンツのデザイン作成

### ISSUE THREAD

**Issue by tomoyahiroe** [shion1305/ynufes-mypage-frontend#74]
### Idea (提案する内容)

Phase2では以下のように、 Homeページにコンテンツを盛ることにする。
- home(page)
    - News(contents) … お知らせのリンクリスト
    - Forms(contents) … 回答フォームのカードリスト
    - Docs(contents) … 資料のリスト
- Settings(page)

上記に則って Formsコンテンツのデザインのみを作成する。

### Impact (提案による変更の影響範囲)

Figmaデザイン

**Comment by Ryo-Sasaki-xxx** [comment]
## todo

- [ ] figmaでデザイン
- [ ] @tomoyahiroe にチェックしてもらう
